### ISSUE TITLE
Add development configuration file for jekyll

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pywps.org#4]
We currently only have 1 configuration file 
_config.yml

The file is only for production and when you used it in jekyll it will build things to run under pywps.org, causing some incorrect URLS
http://blog.parkermoore.de/2014/04/27/clearing-up-confusion-around-baseurl/

For development, better to include also a 

_config_dev.yml 

That contains a different base url
baseurl: /pywps.org

And then  use 
```bash
jekyll server --config _config.yml,_config_dev.yml
jekyll build --config _config.yml,_config_dev.yml
```
Then the website will run on: 
http://127.0.0.1:4000/pywps.org/

@jachym Is this ok with you ? I am not familiar with jekyll

**Comment by tomkralidis** [comment]
@jorgejesus I think you can pass --baseurl as a command line argument? This should override what is in config. I will verify later today.

**Comment by jorgejesus** [comment]
Yes you can, not a problem to set everything on the command line.
Maybe that is enough and better to just add it to the documentation.
I will close the ticket

**Comment by tomkralidis** [comment]
:+1:
