### ISSUE TITLE
upgrade to HTTPS

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pywps.org#8]
@jachym I'm trying to get http://pywps.org to work with HTTPS
and need the following changes to pywps.org DNS:

https://help.github.com/articles/troubleshooting-custom-domains/#custom-domains-configured-with-a-records

Can you update the pywps.org A record to one of those IP addresses
and let me know when done?  I can then configure HTTPS
via GitHub settings accordingly.

**Comment by jachym** [comment]
I hope, this makes it

![obrazek](https://user-images.githubusercontent.com/1460823/51662358-dbdfe000-1fb3-11e9-8e6f-d786875d62fa.png)

**Comment by tomkralidis** [comment]
Works, thanks @jachym !
